name: 'Release'

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/test.yml
      - uses: ./.github/workflows/generateVersion.yml
